registry:
  host: 127.0.0.1
  port: 3211
  protocol: http
  queryApiVersion: v1.3
  basePath: /x-nmos/query

logLevel: info
# Also written to this file (in addition to stdout)
logFile: logs/app.log
appPort: 3000
